#############################################################################################################

name: case_study_movies_project
description: "Showcase project using Flutter, Bloc state management, API integration, authentication and custom UI with modular, reusable design."
publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: '>=3.4.1 <4.0.0'

dev_dependencies:
  flutter_lints: ^3.0.0
  flutter_test:
    sdk: flutter

dependencies:
  flutter:
    sdk: flutter

#############################################################################################################
    
  flutter_bloc: ^9.1.1                        # State Management Solution
  get_it: ^8.2.0                              # Dependency Injection Service
  go_router: ^16.1.0                          # Advanced Navigation & Routing System
  dio: ^5.8.0+1                               # HTTP Networking Service
  flutter_secure_storage: ^9.2.4              # Secure Token Management
  
  lottie: ^3.3.1                              # Optimized JSON Animations
  flutter_animate: ^4.5.2                     # Advanced Animation Builder
  flutter_svg: ^2.0.7                         # SVG Icon Viewer
  flutter_native_splash: ^2.3.3               # Native Splash Screen
  flutter_inset_box_shadow: ^1.0.8            # Custom Gradients
  cupertino_icons: ^1.0.6                     # UI Icons
  readmore: ^3.0.0                            # Expandable Text


#############################################################################################################

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/icons/
    - assets/lottie/
    - assets/fonts/

  fonts:
    - family: EuclidCircularA
      fonts:
        - asset: assets/fonts/Euclid-Circular-A-Regular.ttf
          weight: 400
        - asset: assets/fonts/Euclid-Circular-A-Medium.ttf
          weight: 500
        - asset: assets/fonts/Euclid-Circular-A-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Euclid-Circular-A-Bold.ttf
          weight: 700
    - family: Montserrat
      fonts:
        - asset: assets/fonts/Montserrat-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Montserrat-Black.ttf
          weight: 900

#############################################################################################################

flutter_native_splash:
  color: "#030203"
  color_dark: "#030203"
  image: assets/images/splash_screen.png
  branding: assets/images/splash_screen.png
  image_dark: assets/images/splash_screen.png
  branding_dark: assets/images/splash_screen.png

  android_12:
    icon_background_color: "#030203"
    icon_background_color_dark: "#030203"
    image: assets/images/splash_screen.png
    image_dark: assets/images/splash_screen.png

#############################################################################################################